name: Update Website
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with: 
             repository: nairobilug/nairobilug.or.ke
             submodules: recursive
      - name: Build site
        shell: bash
        run: |
          sudo apt-get install build-essential
          sudo apt-get install python3-setuptools
          sudo apt-get install python3-blinker
          sudo apt-get install python3-markdown
          sudo apt-get install ghp-import
          pip3 install pelican==3.7.1
          pip3 install bs4
          make html
      - name: Commit generated webpage files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add output
          git checkout gh-pages
          git checkout master -- output
          git add *.*
          git checkout master
          git rm output
          git commit -m "Update website" || echo "Nothing to commit"
          git push
